### ISSUE TITLE
Search possibility?

### ISSUE THREAD

**Issue by thiagobfiorenza** [ervwalter/bgg-json#2]
e.g. http://www.boardgamegeek.com/xmlapi/search?search=Crossbows%20and%20Catapults

**Comment by ervwalter** [comment]
Adding search wouldn't be terribly hard, but you'll need to fork the repository and add it yourself in your own copy.   This repository is effectively a set of sample code for people to use on their own projects and on their own servers.  I don't plan to add anything to it.

I updated the readme to make it clear.  Sorry for any confusion.
